<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="<?php echo BASE_URL . 'public/img/icon/iconpage.png';?>">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/style.css">
    <title> CarlitosHostel </title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary shadow-sm">
        <div class="container-fluid">
            <a class="navbar-brand fw-bold" href="<?= BASE_URL ?>Home">CarlitosBuscaHostel.com</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="<?= BASE_URL ?>Rooms">Habitaciones</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="<?= BASE_URL ?>ListCategory">Categorias</a>
                    </li>
                    <?php if($this->user): ?>
                    <li>
                        <a class="nav-link active" href="<?= BASE_URL ?>showReservations">Ver tus reservas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="<?= BASE_URL ?>showAddRoom">Agregar Habitación</a>
                    </li>
                <?php endif; ?>
                </ul>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item me-2">
                        <a class="btn btn-danger" href="<?= BASE_URL ?>showAddReservation">RESERVA YA</a>
                    </li>
                <?php if($this->user): ?>
                    <li class="nav-item">
                        <a class="btn btn-danger" href="<?= BASE_URL ?>logout">Salir</a>
                    </li>
                <?php else: ?>
                    <li class="nav-item">
                        <a class="btn btn-primary" href="<?= BASE_URL ?>showLogin">Iniciar Sesión</a>
                        <a class="btn btn-primary" href="<?= BASE_URL ?>showSignup">Registrarse</a>
                    </li>
                <?php endif; ?>
                </ul>
            </div>
        </div>
    </nav>   