<?php
    require_once 'templates/layouts/header.phtml';
?>
<form method="POST" action="addRoom" class="container mt-4" enctype="multipart/form-data">
    <h2>Completar los datos de la nueva Habitación</h2>
    <div class="mb-3">
        <label for="nombre" class="form-label">Nombre</label>
        <input type="text" name="nombre" class="form-control" id="nombre" placeholder="Nombre de la habitación" required>
    </div>
    <div class="mb-3">
        <label for="capacidad" class="form-label">Capacidad</label>
        <input type="number" name="capacidad" class="form-control" id="capacidad" placeholder="Capacidad de la habitación" required>
    </div>
    <div class="mb-3">
        <label for="precio" class="form-label">Precio</label>
        <input type="number" name="precio" class="form-control" id="precio" placeholder="Precio" required>
    </div>
    <div class="mb-3">
        <label for="tipo" class="form-label">Tipo</label>
        <input type="text" name="tipo" class="form-control" id="tipo" placeholder="Tipo de Habitación" required>
    </div>
    <div class="mb-3">
        <label for="foto_habitacion" class="form-label">Foto de la Habitación</label>
        <input type="file" name="foto_habitacion" accept="image/*" class="form-control" id="foto_habitacion" placeholder="Selecciona la imagen" required>
    </div>

    <button type="submit" class="btn btn-primary">Agregar Habitación</button>
</form>
<?php
    require_once './templates/layouts/footer.phtml';
?>
