<?php
require_once './templates/layouts/header.phtml';
?>
<div class="container">
    <h1>Editar Habitación: <?php echo htmlspecialchars($room->Nombre); ?></h1>
    <form method="POST" action="<?php echo BASE_URL; ?>updateRoom" enctype="multipart/form-data">
        <input type="hidden" name="id_habitacion" value="<?php echo $room->id_habitacion; ?>">
        
        <div class="mb-3">
            <label for="Nombre" class="form-label">Nombre</label>
            <input type="text" class="form-control" name="Nombre" value="<?php echo htmlspecialchars($room->Nombre); ?>" required>
        </div>
        <div class="mb-3">
            <label for="Tipo" class="form-label">Tipo</label>
            <input type="text" class="form-control" name="Tipo" value="<?php echo htmlspecialchars($room->Tipo); ?>" required>
        </div>
        <div class="mb-3">
            <label for="Capacidad" class="form-label">Capacidad</label>
            <input type="number" class="form-control" name="Capacidad" value="<?php echo htmlspecialchars($room->Capacidad); ?>" required>
        </div>
        <div class="mb-3">
            <label for="Precio" class="form-label">Precio</label>
            <input type="number" class="form-control" name="Precio" value="<?php echo htmlspecialchars($room->Precio); ?>" required>
        </div>
        <div class="mb-3">
            <label for="foto_habitacion" class="form-label">Nueva Imagen</label>
            <input type="file" name="foto_habitacion" accept="image/*" class="form-control col-md-6" id="foto_habitacion" placeholder="Selecciona la imagen">
            <small class="form-text text-muted">En caso de no cambiar la imagen, déjalo vacío.</small>
        </div>  
        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
    </form>
    <a href="<?php echo BASE_URL; ?>Rooms" class="btn btn-secondary">Cancelar</a>
</div>
<?php
require_once './templates/layouts/footer.phtml';
?>
