<?php
require_once './templates/layouts/header.phtml';
?>
<div class="container">
    <h1 class="text-center mt-4">Listado de Habitaciones</h1>
    <div class="row">
        <?php foreach ($rooms as $room): ?>
            <div class="col-md-4 mb-4">
                <div class="card">
                <img src="<?php echo $room->foto_habitacion; ?>" class="card-img-top" alt="<?php echo $room->Nombre; ?>">
                    <div class="card-body">
                        <h5 class="card-title"><?= htmlspecialchars($room->Nombre) ?></h5>
                        <a href="<?= BASE_URL ?>RoomsDetails/<?= $room->id_habitacion ?>" class="btn btn-secondary">Ver Detalles</a>
                        <?php if($this->user): ?>
                        <form method="POST" action="<?= BASE_URL ?>deleteRoom" style="display:inline;">
                            <input type="hidden" name="id_habitacion" value="<?= $room->id_habitacion ?>">
                            <button type="submit" class="btn btn-danger" onclick="return confirm('¿Estás seguro de que deseas eliminar esta habitación?');">Eliminar</button>
                        </form>
                        <a href="<?= BASE_URL ?>editRoom?id_habitacion=<?= $room->id_habitacion ?>" class="btn btn-warning">Editar</a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<?php
require_once './templates/layouts/footer.phtml';
?>
